'use strict';

const {
  Paragraph, TextRun, AlignmentType, LineRuleType
} = require('docx');

const {
  CM, FONT, SIZE_BODY, SIZE_HEADING1, SIZE_SUBHEADING, SIZE_TABLE,
  SPACING_15, SPACING_10, INDENT_ALINEA,
  T, TBold, TItalic, TBoldItalic,
  P, PIndent, PCenter, PLeft, PSingle, PEmpty,
  BabTitle, SubBab, SubSubBab,
  ListItem, ListAlpha,
  CaptionTabel, CaptionGambar, FigureBox, ImageFigure,
  createStyledTable
} = require('./helpers');


function getBab2Children() {
  return [
    ...BabTitle('BAB II', 'LANDASAN TEORI'),

    SubBab('2.1', 'Tinjauan Pustaka'),

    SubSubBab('2.1.1', 'Rancang Bangun Sistem Informasi'),
    PIndent([
      T('Rancang bangun sistem informasi merupakan suatu kesatuan aktivitas rekayasa komprehensif yang memadukan dua fase fundamental dalam siklus hidup pengembangan sistem ('),
      TItalic('Software Development Life Cycle/SDLC'),
      T('), yakni fase perancangan konseptual ('),
      TItalic('design'),
      T(') dan fase konstruksi teknis atau pembangunan ('),
      TItalic('development'),
      T('). Menurut Pressman dan Maxim (2015), perancangan sistem informasi adalah proses penerjemahan kebutuhan pengguna ke dalam representasi cetak biru ('),
      TItalic('blueprint'),
      T(') perangkat lunak yang mencakup arsitektur data, arsitektur modul sistem, desain antarmuka, dan prosedur prosedural [7]. Sementara itu, tahap pembangunan mengonversi spesifikasi perancangan tersebut ke dalam bahasa pemrograman yang dapat dieksekusi oleh mesin komputasi.'),
    ]),
    PEmpty(),
    PIndent([
      T('Secara konseptual, sistem informasi didefinisikan sebagai kumpulan komponen yang saling berinteraksi (manusia, teknologi, data, dan prosedur) untuk mengumpulkan, mengolah, menyimpan, dan mendiseminasikan informasi guna mendukung koordinasi operasional, analisis kontrol, dan pengambilan keputusan manajerial dalam suatu organisasi [8]. Dalam konteks industri kuliner dan UMKM, rancang bangun sistem informasi memainkan peran yang sangat strategis. Keterbatasan sumber daya pada UMKM menuntut efisiensi operasional yang optimal. Implementasi sistem informasi manajemen yang dirancang secara tepat guna terbukti mampu mengeliminasi redundansi data, mempercepat aliran komunikasi lintas fungsi, dan meningkatkan akurasi pengambilan keputusan strategis berbasis fakta historis ('),
      TItalic('data-driven decision making'),
      T(') [4].'),
    ]),
    PEmpty(),

    SubSubBab('2.1.2', 'Aplikasi Berbasis Web'),
    PIndent([
      T('Aplikasi berbasis web ('),
      TItalic('web-based application'),
      T(') merupakan kategori perangkat lunak yang beroperasi dengan model komputasi klien-server ('),
      TItalic('client-server architecture'),
      T('), di mana antarmuka pengguna diakses melalui aplikasi peramban web ('),
      TItalic('web browser'),
      T(') melalui protokol jaringan HTTP/HTTPS, sedangkan logika pemrosesan bisnis dan repositori data dikelola oleh peladen ('),
      TItalic('server'),
      T('). Menurut Akmal dan Saputra (2024), keunggulan utama aplikasi berbasis web dibandingkan aplikasi desktop konvensional adalah sifatnya yang '),
      TItalic('cross-platform'),
      T(' dan '),
      TItalic('zero-client installation'),
      T(', di mana pengguna tidak diharuskan melakukan instalasi perangkat lunak khusus pada perangkat keras masing-masing, melainkan cukup memanfaatkan peramban web standar [1]. Distribusi pembaruan ('),
      TItalic('updates'),
      T(') kode program juga dapat dilakukan secara tersentralisasi pada peladen tanpa mengganggu operasional di sisi pengguna.'),
    ]),
    PEmpty(),
    PIndent([
      T('Dalam merancang dan membangun aplikasi '),
      TItalic('RockyTen'),
      T(', penulis memanfaatkan integrasi tumpukan teknologi modern ('),
      TItalic('modern tech stack'),
      T(') yang memiliki keandalan dan performa tinggi, meliputi:'),
    ]),
    ListItem('1', [
      TBold('Next.js 16 (App Router): '),
      T('Merupakan '),
      TItalic('framework'),
      T(' React canggih berbasis JavaScript/TypeScript yang mendukung pola render hibrida, mencakup '),
      TItalic('Server-Side Rendering'),
      T(' (SSR), '),
      TItalic('Static Site Generation'),
      T(' (SSG), serta '),
      TItalic('React Server Components'),
      T(' (RSC). Paradigma '),
      TItalic('App Router'),
      T(' pada Next.js mempermudah manajemen rute berbasis folder, optimasi ukuran paket berkas ('),
      TItalic('bundle size'),
      T('), dan penanganan API internal secara efisien.'),
    ]),
    ListItem('2', [
      TBold('Tailwind CSS v3: '),
      T('Merupakan kerangka kerja desain antarmuka berbasis '),
      TItalic('utility-first CSS'),
      T(' yang memungkinkan perancangan tata letak visual modern, responsif, dan konsisten langsung pada struktur markup komponen. Tailwind CSS mengoptimalkan performa beban halaman dengan memangkas seluruh kelas CSS yang tidak digunakan ('),
      TItalic('purging'),
      T(') pada saat kompilasi produksi, serta mendukung penuh tema mode gelap ('),
      TItalic('dark mode'),
      T(').'),
    ]),
    ListItem('3', [
      TBold('Supabase (Backend-as-a-Service / BaaS): '),
      T('Merupakan platform backend terbuka berbasis mesin basis data relasional PostgreSQL. Supabase menyediakan fungsionalitas autentikasi pengguna terenkripsi, penyimpanan berkas, antarmuka RESTful API instan, serta kapabilitas '),
      TItalic('realtime websocket subscription'),
      T(' yang memungkinkan sinkronisasi data antar peramban secara langsung.'),
    ]),
    ListItem('4', [
      TBold('TypeScript: '),
      T('Merupakan bahasa pemrograman '),
      TItalic('strongly typed'),
      T(' yang memperluas sintaks JavaScript dengan menambahkan sistem pengetikan statis. Penggunaan TypeScript meminimalisir potensi kesalahan pada saat waktu berjalan ('),
      TItalic('runtime errors'),
      T('), meningkatkan kualitas dokumentasi kode, dan mempercepat kolaborasi pengembangan.'),
    ]),
    PEmpty(),

    SubSubBab('2.1.3', 'Role-Based Access Control (RBAC)'),
    PIndent([
      T('Keamanan informasi merupakan aspek krusial dalam sistem informasi korporasi yang menampung data kinerja dan finansial sensitif. '),
      TItalic('Role-Based Access Control'),
      T(' (RBAC) adalah suatu pendekatan kontrol akses berbasis kebijakan di mana hak akses pengguna terhadap objek sistem ditentukan berdasarkan fungsi jabatan atau peran ('),
      TItalic('role'),
      T(') yang diemban pengguna dalam struktur organisasi, bukan berdasarkan identitas pengguna secara individual [3]. Standar model RBAC yang dirumuskan oleh NIST ('),
      TItalic('National Institute of Standards and Technology'),
      T(') mengidentifikasi empat tingkatan model utama, yakni:'),
    ]),
    ListAlpha('a', [
      TBold('Core RBAC (RBAC0): '),
      T('Model dasar yang mendefinisikan hubungan dasar antara tiga entitas utama: Pengguna ('),
      TItalic('Users'),
      T('), Peran ('),
      TItalic('Roles'),
      T('), dan Hak Akses ('),
      TItalic('Permissions'),
      T('). Seorang pengguna dapat diasosiasikan dengan satu atau lebih peran, dan setiap peran memiliki kumpulan izin akses spesifik.'),
    ]),
    ListAlpha('b', [
      TBold('Hierarchical RBAC (RBAC1): '),
      T('Model yang menambahkan struktur hirarki peran ('),
      TItalic('role hierarchy'),
      T('), di mana peran tingkat atas mewarisi hak akses dari peran-peran di bawahnya secara otomatis.'),
    ]),
    ListAlpha('c', [
      TBold('Constrained RBAC (RBAC2): '),
      T('Model yang menerapkan aturan pembatasan pemisahan wewenang ('),
      TItalic('Separation of Duties/SoD'),
      T('), baik secara statis maupun dinamis guna mencegah terjadinya konflik kepentingan ('),
      TItalic('conflict of interest'),
      T(').'),
    ]),
    ListAlpha('d', [
      TBold('Unified RBAC (RBAC3): '),
      T('Model gabungan yang mengonsolidasikan prinsip hirarki peran (RBAC1) dan pembatasan pemisahan wewenang (RBAC2) ke dalam satu kesatuan sistem keamanan.'),
    ]),
    PEmpty(),
    PIndent([
      T('Implementasi model keamanan RBAC berlandaskan pada prinsip keistimewaan terendah ('),
      TItalic('Principle of Least Privilege'),
      T('), yakni setiap subjek hanya diberikan wewenang minimum yang secara mutlak diperlukan untuk menyelesaikan tugas resminya. Pada aplikasi '),
      TItalic('RockyTen'),
      T(', RBAC diimplementasikan secara granular pada tingkat komponen dan lapisan query data, membagi wewenang pengguna ke dalam tiga peran:'),
    ]),
    ListItem('1', [
      TBold('Developer (Pengembang): '),
      T('Memiliki wewenang superadministrator atas seluruh data divisi, dilengkapi panel pemantauan kendala sistem, log galat ('),
      TItalic('error log'),
      T('), serta panel '),
      TItalic('Role Switcher'),
      T(' untuk keperluan pengujian.'),
    ]),
    ListItem('2', [
      TBold('Owner (Pemilik Perusahaan): '),
      T('Memiliki wewenang pemantauan penuh ('),
      TItalic('read/view access'),
      T(') atas seluruh metrik kinerja dan target di seluruh lima divisi tanpa dibebani akses teknis debugging.'),
    ]),
    ListItem('3', [
      TBold('PIC (Person In Charge / Pimpinan Divisi): '),
      T('Memiliki hak akses operasional (baca, tambah, ubah) yang terisolasi secara ketat hanya pada data milik divisinya sendiri (IT, Finance, Kitchen, Service, atau Marketing), mencegah risiko kebocoran data antar departemen.'),
    ]),
    PEmpty(),

    SubSubBab('2.1.4', 'Metodologi Traction — Level 10 Meeting'),
    PIndent([
      T('Dalam buku fundamentalnya berjudul '),
      TItalic('Traction: Get a Grip on Your Business'),
      T(' (2011), Gino Wickman memperkenalkan kerangka manajemen holistik yang dinamakan '),
      TItalic('Entrepreneurial Operating System'),
      T(' (EOS). EOS dikembangkan untuk membantu para pendiri bisnis dan tim manajemen mengatasi berbagai friksi internal organisasi, seperti frustrasi atas target yang tidak tercapai, ketiadaan keselarasan tim, dan hilangnya kendali operasional [5]. EOS bertumpu pada penguatan enam pilar kunci bisnis, yaitu: Visi ('),
      TItalic('Vision'),
      T('), Sumber Daya Manusia ('),
      TItalic('People'),
      T('), Data ('),
      TItalic('Data'),
      T('), Isu Permasalahan ('),
      TItalic('Issues'),
      T('), Proses ('),
      TItalic('Process'),
      T('), dan Daya Cengkeram/Eksekusi ('),
      TItalic('Traction'),
      T(').'),
    ]),
    PEmpty(),
    PIndent([
      T('Komponen paling praktis dan transformatif dalam pilar '),
      TItalic('Traction'),
      T(' adalah format rapat koordinasi mingguan yang disebut '),
      TItalic('Level 10 Meeting'),
      T(' (L10). Dinamakan "Level 10" karena format ini dirancang khusus untuk memastikan bahwa setiap rapat mingguan bernilai efisiensi 10 (pada skala 1–10) bagi seluruh peserta rapat. Rapat L10 memiliki durasi baku 90 menit dengan struktur agenda yang disiplin dan tidak boleh diubah:'),
    ]),
    ListItem('1', [
      TBold('Good News / Headlines (5 Menit): '),
      T('Membuka sesi rapat dengan membagikan kabar positif personal dan profesional, serta menyampaikan pengumuman penting ('),
      TItalic('Headlines'),
      T(') terkait pelanggan atau karyawan untuk membangun energi positif tim.'),
    ]),
    ListItem('2', [
      TBold('Scorecard / Scoreboard Review (5 Menit): '),
      T('Meninjau secara cepat metrik-metrik kunci operasional mingguan guna memastikan setiap indikator berada pada jalur yang diharapkan ('),
      TItalic('on track'),
      T('). Indikator yang menyimpang dari target ('),
      TItalic('off track'),
      T(') tidak diperdebatkan pada tahap ini, melainkan langsung dicatat ke dalam daftar '),
      TItalic('Issues'),
      T('.'),
    ]),
    ListItem('3', [
      TBold('Rock Review (5 Menit): '),
      T('Mengevaluasi status pencapaian target kuartalan 90 hari ('),
      TItalic('Rocks'),
      T(') milik masing-masing PIC divisi. Jika suatu '),
      TItalic('Rock'),
      T(' terancam gagal ('),
      TItalic('off track'),
      T('), target tersebut segera diekskalasikan ke daftar '),
      TItalic('Issues'),
      T('.'),
    ]),
    ListItem('4', [
      TBold('Customer / Employee Headlines (5 Menit): '),
      T('Meninjau informasi atau masukan berharga dari pelanggan dan karyawan yang memerlukan perhatian tim.'),
    ]),
    ListItem('5', [
      TBold('To-Do List Review (5 Menit): '),
      T('Memeriksa penyelesaian daftar tugas komitmen 7 hari yang dihasilkan dari rapat minggu sebelumnya. Standar keberhasilan tim adalah minimal 90% tugas berstatus selesai ('),
      TItalic('done'),
      T(').'),
    ]),
    ListItem('6', [
      TBold('IDS — Identify, Discuss, Solve (60 Menit): '),
      T('Merupakan jantung dari rapat L10, di mana mayoritas waktu (60 menit) dialokasikan untuk menyelesaikan permasalahan operasional paling krusial secara tuntas. Tim dilarang sekadar membahas permukaan masalah, melainkan wajib menelusuri akar penyebab ('),
      TItalic('Identify'),
      T('), mendiskusikan opsi solusi secara objektif ('),
      TItalic('Discuss'),
      T('), dan menyepakati tindakan konkret yang dialihkan menjadi tugas baru ('),
      TItalic('Solve'),
      T(').'),
    ]),
    ListItem('7', [
      TBold('Conclusion / Wrap-Up (5 Menit): '),
      T('Merekapitulasi tugas baru pada '),
      TItalic('To-Do List'),
      T(', menyepakati pesan yang perlu disampaikan ke tim eksternal, dan memberikan penilaian ('),
      TItalic('rating'),
      T(') atas efektivitas rapat.'),
    ]),
    PEmpty(),
    PIndent([
      T('Pada aplikasi '),
      TItalic('RockyTen'),
      T(', konsep '),
      TItalic('Rocks'),
      T(' dan '),
      TItalic('Scoreboard'),
      T(' diintegrasikan secara inovatif. '),
      TItalic('Rocks'),
      T(' bertindak sebagai sasaran makro 90 hari, di mana progres keberhasilannya dapat ditopang oleh sub-metrik mingguan di '),
      TItalic('Scoreboard'),
      T('. Selain menampung sub-metrik yang terikat dengan '),
      TItalic('Rocks'),
      T(', modul '),
      TItalic('Scoreboard'),
      T(' juga mendukung metrik mandiri ('),
      TItalic('standalone metrics'),
      T('), yakni metrik operasional rutin harian/bulanan yang wajib terus dipantau terlepas dari adanya target 90 hari tertentu.'),
    ]),
    PEmpty(),

    SubSubBab('2.1.5', 'Metode Waterfall'),
    PIndent([
      T('Metode '),
      TItalic('Waterfall'),
      T(' (model air terjun) merupakan salah satu metodologi rekayasa perangkat lunak klasik tertua yang pertama kali dipublikasikan oleh Dr. Winston W. Royce pada tahun 1970 dan dikembangkan lebih lanjut dalam literatur rekayasa perangkat lunak oleh Roger S. Pressman [7]. Metode ini menganut paradigma sekuensial linier ('),
      TItalic('linear sequential lifecycle model'),
      T('), di mana setiap fase kegiatan pengembangan perangkat lunak harus diselesaikan, diverifikasi, dan didokumentasikan secara tuntas sebelum melangkah ke fase berikutnya, layaknya aliran air terjun yang mengalir ke hilir tanpa berbalik arah.'),
    ]),
    PEmpty(),
    PIndent([
      T('Fase-fase utama dalam metode Waterfall meliputi:'),
    ]),
    ListItem('1', [
      TBold('Analisis Kebutuhan (Requirements Analysis): '),
      T('Menggali, mengidentifikasi, dan mendokumentasikan seluruh kebutuhan fungsional dan non-fungsional sistem melalui observasi langsung dan wawancara dengan para pemangku kepentingan.'),
    ]),
    ListItem('2', [
      TBold('Perancangan Sistem (System Design): '),
      T('Menyusun arsitektur sistem, memodelkan aliran data menggunakan Data Flow Diagram (DFD), merancang struktur tabel basis data (ERD), merancang antarmuka visual pengguna (UI/UX), serta memetakan aturan otorisasi hak akses (RBAC).'),
    ]),
    ListItem('3', [
      TBold('Implementasi (Implementation / Coding): '),
      T('Menerjemahkan dokumen perancangan ke dalam baris-baris kode program nyata menggunakan teknologi terpilih (Next.js, Tailwind CSS, Supabase, TypeScript).'),
    ]),
    ListItem('4', [
      TBold('Pengujian Sistem (Testing & Verification): '),
      T('Menguji keandalan setiap fungsi perangkat lunak menggunakan metode Black Box Testing guna memastikan sistem terbebas dari kesalahan logika dan memenuhi seluruh spesifikasi awal.'),
    ]),
    ListItem('5', [
      TBold('Penerapan dan Pemeliharaan (Deployment & Maintenance): '),
      T('Menerapkan perangkat lunak ke lingkungan peladen produksi (Vercel) dan melakukan evaluasi performa serta penyesuaian operasional bersama pengguna akhir.'),
    ]),
    FigureBox('DIAGRAM METODE PENGEMBANGAN WATERFALL', 'Fase 1: Kebutuhan → Fase 2: Desain → Fase 3: Pengodean → Fase 4: Pengujian → Fase 5: Penerapan'),
    CaptionGambar('Gambar 2.1', 'Alur Metode Pengembangan Perangkat Lunak Waterfall'),

    PIndent([
      T('Pemilihan metode '),
      TItalic('Waterfall'),
      T(' dalam penelitian Praktik Kerja Lapangan ini didasarkan pada karakteristik proyek yang memiliki rentang waktu pasti (3 bulan / 13 minggu), ruang lingkup permasalahan yang telah terdefinisi secara jelas sejak awal bersama pihak PT Garciafood Nusantara Gemilang, serta tuntutan dokumentasi akademik yang terstruktur dan sistematis sesuai standar pedoman Politeknik Ganesha Medan.'),
    ]),
    PEmpty(),

    SubBab('2.2', 'Penelitian Terkait'),
    PIndent([
      T('Guna memperkaya landasan ilmiah, memetakan posisi penelitian, dan membuktikan kebaruan sistem yang dibangun, penulis menelaah lima rujukan penelitian terdahulu yang relevan dengan topik perancangan sistem informasi berbasis web, manajemen UMKM, dan kontrol akses RBAC sebagaimana dirangkum pada Tabel 2.1 di bawah ini:'),
    ]),
    PEmpty(),
    CaptionTabel('Tabel 2.1', 'Perbandingan Hasil Penelitian Terkait'),
    createStyledTable(
      ['No', 'Peneliti & Tahun', 'Judul Penelitian', 'Metode', 'Hasil & Temuan Penelitian'],
      [
        ['1', 'Akmal & Saputra (2024)', 'Perancangan Website Company Profile Menggunakan PHP dan MySQL', 'Waterfall', 'Membangun media informasi perusahaan berbasis web yang meningkatkan visibilitas digital, namun sistem bersifat statis tanpa fitur manajemen kinerja internal.'],
        ['2', 'Arianto et al. (2022)', 'Media Company Profile PT. Multipedia Teknika Indonesia Berbasis Web', 'Waterfall', 'Menghasilkan antarmuka web interaktif untuk menyajikan portofolio dan layanan perusahaan, namun tidak mengakomodasi segregasi hak akses lintas departemen.'],
        ['3', 'Supriyadi et al. (2024)', 'Rancang Bangun Company Profile Berbasis Web Menggunakan Metode Waterfall', 'Waterfall', 'Mengembangkan portal profil bisnis UMKM makanan beku APM Frozen Food guna memperluas jangkauan pasar, belum memiliki modul evaluasi kinerja tim.'],
        ['4', 'Sandhu et al. (1996)', 'Role-Based Access Control Models (NIST)', 'Konseptual Formal', 'Merumuskan standar acuan industri untuk arsitektur keamanan kontrol akses berbasis peran (RBAC0-RBAC3) yang menjadi fondasi keamanan data modern.'],
        ['5', 'Widiyatni et al. (2021)', 'Implementasi RBAC pada Sistem Informasi Manajemen Berbasis Web', 'Prototyping', 'Menerapkan hak akses bertingkat untuk mengamankan data transaksi internal organisasi, membuktikan efektivitas RBAC dalam mencegah kebocoran data sensitif.'],
      ],
      [600, 1600, 2400, 1200, 2900]
    ),
    PEmpty(),
    PIndent([
      T('Berdasarkan komparasi penelitian terkait pada Tabel 2.1, tampak jelas bahwa mayoritas penelitian terdahulu mengenai sistem berbasis web di ranah UMKM (Akmal & Saputra, 2024; Arianto et al., 2022; Supriyadi et al., 2024) masih terbatas pada pembuatan media profil perusahaan ('),
      TItalic('company profile'),
      T(') statis untuk kepentingan eksternal. Sementara itu, penelitian keamanan akses (Sandhu et al., 1996; Widiyatni et al., 2021) menunjukkan bahwa proteksi data internal memerlukan segregasi peran yang disiplin. Kebaruan dan kontribusi unik dari penelitian aplikasi '),
      TItalic('RockyTen'),
      T(' ini adalah menggabungkan sistem manajemen kinerja operasional berbasis metodologi '),
      TItalic('Traction Level 10 Meeting'),
      T(' yang dinamis dengan arsitektur proteksi keamanan RBAC tiga tingkat (Developer, Owner, PIC) yang diterapkan secara spesifik pada 5 divisi operasional bisnis kuliner PT Garciafood Nusantara Gemilang.'),
    ]),
    PEmpty(),

    SubBab('2.3', 'Kerangka Pemikiran'),
    PIndent([
      T('Kerangka pemikiran merupakan struktur logis yang menjelaskan keterkaitan antara permasalahan nyata di tempat magang, pendekatan teoritis yang diadopsi, alur metodologi rekayasa yang ditempuh, hingga tercapainya tujuan yang diharapkan. Alur kerangka pemikiran penelitian ini disajikan pada Gambar 2.2.'),
    ]),
    PEmpty(),
    FigureBox('BAGAN ALIR KERANGKA PEMIKIRAN METODOLOGIS PENELITIAN', 'Identifikasi Masalah Manual → Landasan Teori (Traction & RBAC) → Metode Waterfall → Stack Teknologi → Solusi Terwujud (RockyTen)'),
    CaptionGambar('Gambar 2.2', 'Diagram Alir Kerangka Pemikiran Metodologis Penelitian'),
    PEmpty(),
    PIndent([
      T('Penjelasan tahapan logis dari kerangka pemikiran di atas adalah sebagai berikut:'),
    ]),
    ListItem('1', [
      TBold('Identifikasi Masalah Operasional: '),
      T('PT Garciafood Nusantara Gemilang menghadapi hambatan koordinasi kinerja antar 5 divisi, pelaksanaan rapat mingguan yang tidak terstruktur, pelacakan target yang tidak terpusat, serta kekhawatiran atas kerahasiaan data keuangan dan kinerja tanpa proteksi hak akses.'),
    ]),
    ListItem('2', [
      TBold('Pendekatan Solusi & Landasan Teori: '),
      T('Penulis mengadopsi kerangka kerja manajerial '),
      TItalic('Traction Level 10 Meeting'),
      T(' oleh Gino Wickman untuk menstrukturkan rapat dan pelacakan metrik, serta standar keamanan '),
      TItalic('Role-Based Access Control'),
      T(' (RBAC) oleh Sandhu et al. guna membatasi wewenang antar divisi.'),
    ]),
    ListItem('3', [
      TBold('Metode Rekayasa Perangkat Lunak: '),
      T('Menerapkan tahapan terstruktur metode '),
      TItalic('Waterfall'),
      T(' (Analisis Kebutuhan, Perancangan Sistem, Implementasi Kode, Pengujian Sistem, dan Evaluasi Akhir).'),
    ]),
    ListItem('4', [
      TBold('Teknologi Pembangun: '),
      T('Menggunakan tumpukan teknologi modern Next.js 16 (App Router), Supabase (PostgreSQL), Tailwind CSS, dan TypeScript yang di-*deploy* pada Vercel Cloud Platform.'),
    ]),
    ListItem('5', [
      TBold('Hasil yang Dicapai: '),
      T('Terwujudnya aplikasi '),
      TItalic('RockyTen'),
      T(' berbasis web yang memiliki 5 modul kolaboratif (Scoreboard, Rocks, Headlines, To-Do, Issues) dengan pengamanan RBAC 3 tingkat wewenang yang siap digunakan secara produktif di PT Garciafood Nusantara Gemilang.'),
    ]),
  ];
}

module.exports = {
  getBab2Children,
};
